
from pathlib import Path
from datetime import datetime
import os


REPORT_FOLDER = Path("reports")


def generate_report(folder_path, stats, total):

    REPORT_FOLDER.mkdir(exist_ok=True)

    report_file = REPORT_FOLDER / "organization_report.txt"

    current_time = datetime.now().strftime(
        "%d %B %Y, %H:%M:%S"
    )

    report = f"""
========================================
        FILE ORGANIZER PRO REPORT
========================================

Date:
{current_time}

Selected Folder:
{folder_path}

----------------------------------------
FILE STATISTICS
----------------------------------------

Images       : {stats.get("Images", 0)}
Documents    : {stats.get("Documents", 0)}
PDFs         : {stats.get("PDFs", 0)}
Videos       : {stats.get("Videos", 0)}
Audio        : {stats.get("Audio", 0)}
Archives     : {stats.get("Archives", 0)}
Programs     : {stats.get("Programs", 0)}
Others       : {stats.get("Others", 0)}

----------------------------------------
TOTAL FILES : {total}
----------------------------------------

Status:
Organization completed successfully.

========================================
       Generated by File Organizer Pro
========================================
"""

    with open(
        report_file,
        "w",
        encoding="utf-8"
    ) as file:

        file.write(report)

    # Automatically open the report
    os.startfile(
        report_file.resolve()
    )

    return report_file

